use_frameworks!

source 'https://github.com/oneAlon/YAPodSpecs.git'
source 'git@github.com:CocoaPods/Specs.git'

target 'SYABasicUIKit_Example' do
  pod 'SYABasicUIKit', :path => '../'

  target 'SYABasicUIKit_Tests' do
    inherit! :search_paths

    
  end
end
